import { WeChat } from "./module/Share/share";

const {ccclass, property, requireComponent} = cc._decorator;

@ccclass
export default class NewClass extends cc.Component {

    @property(false)
    localTest: boolean = false;

    @property("")
    clientTestVersion: string = "1.0.0";

    @property(cc.Label)
    testVersion: cc.Label = null;

    start () {
        window.initMgr();
        WeChat.setShare(location.href);
        cc.fx.GameConfig.init(this.localTest);
        this.testVersion.string = this.clientTestVersion;

        //24年 25年9万   27年
        // setTimeout(() => {
        //     for(let i=0; i<10;i++){
        //         let num = cc.fx.GameTool.getSeedRandom(1,10);
        //         console.log(num);
        //     }
        // }, 100);
        // 
        
    }

    setRank(){
        let data = {
            "totleTimes": 8759,
            "accuracy": 80,
        }
        cc.fx.GameTool.setRank(data);
    }

    //开始游戏，跳转至引导页面
    startGame(){
  
        setTimeout(() => {
            cc.director.loadScene("GuideScene");
        }, 100);
        // cc.director.loadScene("GuideScene");
    }
    //备用，用来测试跳转 指定关卡
    clickBtn(event,data){
        // cc.fx.GameConfig.GM_INFO.custom = parseInt(data);
        cc.director.loadScene("GameScene");
    }   
    //打开排行榜
    openRank(){
        setTimeout(() => {
            cc.director.loadScene("RankScene");
        }, 100);
    }
    
    protected update(dt: number): void {
    }
}
